server.port: 8011


spring:
    application:
        name: mpp-person
    jackson:
        property-naming-strategy: SNAKE_CASE

    data.mongodb.uri: mongodb://mpp-person-mongodb/mpp-person
#    data.mongodb.uri: mongodb://localhost:27017/mpp-person

#logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
#spring.http.log-request-details: true
